### ISSUE TITLE
0.6.4 breaks compiling Ink files on Windows

### ISSUE THREAD

**Issue by wilg** [inkle/ink-unity-integration#27]
```
Unhandled error occurred compiling Ink file [InkFile: filePath=Assets/_Story/Episodes/gameplay_demo/gameplay_demo.ink]! Please report following error as a bug:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'ink-engine-runtime, Version=1.0.6198.27218, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)

UnityEngine.Debug:LogError(Object)
Ink.UnityIntegration.InkCompiler:Delay() (at Assets/Plugins/Ink/Editor/Compiler/InkCompiler.cs:186)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

![capture](https://cloud.githubusercontent.com/assets/54353/21596916/1ab2a2c6-d0f7-11e6-8b4d-1101166e3e0d.PNG)

Compiling Ink files works on my Mac with the same Unity project. Ink 0.6.4, Unity 5.5.0f3. I tried deleting the Ink installation and installing fresh, which did not help.

I tried 0.6.3 which does work so it's probably that compiler refactor mentioned in the release notes.

**Comment by joethephish** [comment]
Is anyone else seeing this?

**Comment by tomkail** [comment]
Since we're not supporting old versions and there's been no update I'm closing this.
